### ISSUE TITLE
can i use it in nodejs env

### ISSUE THREAD

**Issue by hccde** [exif-js/exif-js#151]
hi,thanks for this great jslib ,but it seems cant use in node runtime.do you have a plan to support node runtime.or are you willing to accept a 'node-runtime' support

**Comment by edemaine** [comment]
FWIW, I just tried this on Node:
```js
EXIF = require('exif-js')
fs = require('fs')
jpeg = fs.readFileSync('20160725_145633.jpg')
EXIF.readFromBinaryFile(jpeg.buffer)  // convert Node's Buffer to JS ArrayBuffer
```
Unfortunately, I get an error, because Node doesn't have the notion of `Blob`s:
```
ReferenceError: Blob is not defined
    at readThumbnailImage (C:\Users\edemaine\node_modules\exif-js\exif.js:720:49)
    at readEXIFData (C:\Users\edemaine\node_modules\exif-js\exif.js:837:29)
    at findEXIFinJPEG (C:\Users\edemaine\node_modules\exif-js\exif.js:449:24)
    at Function.EXIF.readFromBinaryFile (C:\Users\edemaine\node_modules\exif-js\exif.js:1050:16)
```

**Comment by hccde** [comment]
@edemaine  i have done a unfinished work for this lib a few months ago , found many problems at the same time.you have to rewrite some code and change api associated with env. if i can spare some time this Sunday , i will try to finish it.

**Comment by hccde** [comment]
there are some jslib which has meet our needs in npm. i add several functions for this lib to run correctly in node-env for some reason,if someone wants to use it , see [node-exif](git@github.com:hccde/node-exif.git)

**Comment by ianldgs** [comment]
Workaround with JSDOM:

```js
require('canvas-prebuilt')

const { JSDOM } = require('jsdom')

const dom = new JSDOM('', {
    resources: 'usable',
})

global.atob = require('atob')
global.btoa = require('btoa')

global.window = global.self = dom.window

const exif = require('exif-js')
```
