### ISSUE TITLE
high dpi image (600dpi) will cause Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by abrcdf1023** [exif-js/exif-js#63]
exif.js:594  Uncaught RangeError: Offset is outside the bounds of the DataView

If choose image's dpi higher then 600,it will crash.

I currently add try catch to solve this issue.

But i wonder it's can be fix or maybe no one will choose 600dpi images?

**Comment by sj00** [comment]
I have similar issue for images with 'Resolution unit: 2'

Example image: [http://68.media.tumblr.com/eb2eb9bf530f14bee20625d983073289/tumblr_ogydlmOGnA1qlcz08o1_75sq.jpg](url)

Stack Trace: 
```
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at getStringFromDB (exif.js:740)
    at findXMPinJPEG (exif.js:862)
    at handleBinaryFile (exif.js:372)
    at FileReader.fileReader.onload (exif.js:412)
```

**Comment by thynson** [comment]
@sj00 I successfully parsed your image with latest EXIF in node 7.8.0. However it still crash for [this image](https://cloud.githubusercontent.com/assets/895964/23978874/421543a0-0a31-11e7-841c-bc0c8f961c5a.jpg)

StackTrace:
```
RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (<anonymous>)
    at readTagValue (/Users/lanxingcan/Workspace/vote/node_modules/exif-js/exif.js:593:40)
    at readTags (/Users/lanxingcan/Workspace/vote/node_modules/exif-js/exif.js:570:25)
    at readEXIFData (/Users/lanxingcan/Workspace/vote/node_modules/exif-js/exif.js:820:23)
    at findEXIFinJPEG (/Users/lanxingcan/Workspace/vote/node_modules/exif-js/exif.js:447:24)
    at Function.EXIF.readFromBinaryFile (/Users/lanxingcan/Workspace/vote/node_modules/exif-js/exif.js:1004:16)
    at repl:1:6
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
```

**Comment by maikusch** [comment]
Same problem here. Does anybody knows how to get fixed that for the moment?
I get this error on image-upload. The error occurs, but the image regardless is uploaded.

**Comment by ercinakcay** [comment]
I only need orientation data from EXIF so I solved my problem with using this code and extracting  exif.js.

```

getOrientation = function (file, callback) {
    var reader = new window.FileReader();
    reader.onload = function (e) {

        var view = new window.DataView(e.target.result);
        if (view.getUint16(0, false) != 0xFFD8) {
            return callback(-2);
        }
        var length = view.byteLength, offset = 2;
        while (offset < length) {
            var marker = view.getUint16(offset, false);
            offset += 2;
            if (marker == 0xFFE1) {
                if (view.getUint32(offset += 2, false) != 0x45786966) {
                    return callback(-1);
                }
                var little = view.getUint16(offset += 6, false) == 0x4949;
                offset += view.getUint32(offset + 4, little);
                var tags = view.getUint16(offset, little);
                offset += 2;
                for (var i = 0; i < tags; i++) {
                    if (view.getUint16(offset + (i * 12), little) == 0x0112) {
                        return callback(view.getUint16(offset + (i * 12) + 8, little));
                    }

                }
            } else if ((marker & 0xFF00) != 0xFF00) {
                break;
            } else {
                offset += view.getUint16(offset, false);
            }
        }
        return callback(-1);
    };
    reader.readAsArrayBuffer(file);
}
```

**Comment by simplefeel** [comment]
me too, Uncaught RangeError: Offset is outside the bounds of the DataView~how to solve?

**Comment by sasanikolic90** [comment]
Our error message stack using Drupal and dropzone.js is the following:
```
exif.js?v=2.3.0:563 Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint16 (<anonymous>)
    at readTags (exif.js?v=2.3.0:563)
    at readEXIFData (exif.js?v=2.3.0:783)
    at findEXIFinJPEG (exif.js?v=2.3.0:449)
    at handleBinaryFile (exif.js?v=2.3.0:370)
    at getImageData (exif.js?v=2.3.0:386)
    at Function.EXIF.getData (exif.js?v=2.3.0:983)
    at g (dropzone.min.js?v=4.0.1:1)
    at HTMLImageElement.i.onload (dropzone.min.js?v=4.0.1:1)
```

I believe the issue there is that in some cases, tag values are more than the max unsigned 16 big integer. Something like this would work:
```
if (tag !== undefined) {
  tagValue = readTagValue(file, entryOffset, tiffStart, dirStart, bigEnd);
  if (tagValue > 65535) { // tag value should not be more than max unsigned 16-bit integer
    if (debug) {
      console.log("Offset is outside the bounds of the DataView");
    }
  }
  else {
    tags[tag] = readTagValue(file, entryOffset, tiffStart, dirStart, bigEnd);
  }
}
```
